# .github/workflows/main.yml
name: CI/CD using Shared Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  use-shared-workflow:
    uses: 123shivamsinha/shared-library/.github/workflows/ci-cd.yaml@main
    with:
      run-tests: true
      run-build: true
